### PR TITLE
Update people.yml

### PR DESCRIPTION
**Pull request by gundersonnm**
Add Nicole to people page

### CODE REVIEW

**Comment by crheckman** [comment]
@gundersonnm this commit doesn't include a photo; could you append with one?

**Comment by gundersonnm** [comment]
> @gundersonnm this commit doesn't include a photo; could you append with one?

**Comment by crheckman** [comment]
@gundersonnm sorry to bug but the image isn't part of the commit and the PR was closed (I'm guessing involuntarily). Could you give it another shot?

**Comment by gundersonnm** [comment]
> @gundersonnm sorry to bug but the image isn't part of the commit and the PR was closed (I'm guessing involuntarily). Could you give it another shot?

I believe I just added the image as part of the PR... Let me know if this isn't so.

**Comment by crheckman** [comment]
It looks like the image isn't being included as part of this PR, still --- I can tell because at the top it says only 1 file is changed (_data/people.yml)

**Comment by gundersonnm** [comment]
> It looks like the image isn't being included as part of this PR, still --- I can tell because at the top it says only 1 file is changed (_data/people.yml)

Maybe now?

**Pull request merged**
